version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:16'  # using Node.js image version 16
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Railway
          command: |
            sudo npm uninstall -g railway || true # Uninstall old Railway CLI if it exists (ignoring failure)
            sudo npm install -g npm@latest # Update to the latest version of npm
            sudo npm install -g @railway/cli # Install new Railway CLI
            echo "RAILWAY_TOKEN=your-railway-token" >> $HOME/.railway
      - run:
          name: Build Dockerfile
          command: |
            docker build -t myapp .
      - run:
          name: Run Dockerfile
          command: |
            docker run -d -p 8000:8000 myapp
  deploy:
    docker:
      - image: 'circleci/node:16'  # using Node.js image version 16
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Railway
          command: |
            sudo npm uninstall -g railway || true # Uninstall old Railway CLI if it exists (ignoring failure)
            sudo npm install -g npm@latest # Update to the latest version of npm
            sudo npm install -g @railway/cli # Install new Railway CLI
            echo "RAILWAY_TOKEN=your-railway-token" >> $HOME/.railway
      - run:
          name: Build Dockerfile
          command: |
            docker build -t myapp .
      - run:
          name: Run and Deploy Dockerfile
          command: |
            docker run -d -p 8000:8000 myapp
      - run:
          name: Deploy to Railway
          command: |
            railway up --detach
  redeploy:
    docker:
      - image: 'circleci/node:16'  # using Node.js image version 16
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Railway
          command: |
            sudo npm uninstall -g railway || true # Uninstall old Railway CLI if it exists (ignoring failure)
            sudo npm install -g npm@latest # Update to the latest version of npm
            sudo npm install -g @railway/cli # Install new Railway CLI
            echo "RAILWAY_TOKEN=your-railway-token" >> $HOME/.railway
      - run:
          name: Build Dockerfile
          command: |
            docker build -t myapp .
      - run:
          name: Run and Deploy Dockerfile
          command: |
            docker run -d -p 8000:8000 myapp
      - run:
          name: Deploy to Railway
          command: |
            railway up --detach

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/  # Allow all tags
      - deploy:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/  # Ignore all tags
            branches:
              only: /.*/  # Allow all branches
      - redeploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
