version: 2.1
jobs:
  build:
    docker:
      - image: 'docker:19.03.13'  # using Docker image
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Dockerfile
          command: |
            docker build -t myapp .
      - run:
          name: Run Dockerfile
          command: |
            docker run -d -p 8000:8000 myapp
  deploy:
    docker:
      - image: 'docker:19.03.13'  # using Docker image
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Dockerfile
          command: |
            docker build -t myapp .
      - run:
          name: Run and Deploy Dockerfile
          command: |
            docker run -d -p 8000:8000 myapp
            railway up --detach

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/   # Allow all tags
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/   # Ignore all branches

