version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:14'  # using Node.js image
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Railway
          command: |
            sudo npm install -g railway
            echo "RAILWAY_TOKEN=your-railway-token" >> $HOME/.railway
      - run:
          name: Build Dockerfile
          command: |
            docker build -t myapp .
  deploy:
    docker:
      - image: 'circleci/node:14'  # using Node.js image
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Railway
          command: |
            sudo npm install -g railway
            echo "RAILWAY_TOKEN=your-railway-token" >> $HOME/.railway
      - run:
          name: Deploy to Railway
          command: |
            echo "Starting deployment to Railway"
            railway up --detach
            echo "Finished deployment to Railway"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/   # Allow all tags
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/   # Ignore all branches
